/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestLeavesRequestLeaveRouteImport } from './routes/request-leaves/request-leave'
import { Route as LeavesListRequestsListRouteImport } from './routes/leaves-list/requests-list'

const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestLeavesRequestLeaveRoute =
  RequestLeavesRequestLeaveRouteImport.update({
    id: '/request-leaves/request-leave',
    path: '/request-leaves/request-leave',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeavesListRequestsListRoute = LeavesListRequestsListRouteImport.update({
  id: '/leaves-list/requests-list',
  path: '/leaves-list/requests-list',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/employee': typeof EmployeeRoute
  '/manager': typeof ManagerRoute
  '/leaves-list/requests-list': typeof LeavesListRequestsListRoute
  '/request-leaves/request-leave': typeof RequestLeavesRequestLeaveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/employee': typeof EmployeeRoute
  '/manager': typeof ManagerRoute
  '/leaves-list/requests-list': typeof LeavesListRequestsListRoute
  '/request-leaves/request-leave': typeof RequestLeavesRequestLeaveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/employee': typeof EmployeeRoute
  '/manager': typeof ManagerRoute
  '/leaves-list/requests-list': typeof LeavesListRequestsListRoute
  '/request-leaves/request-leave': typeof RequestLeavesRequestLeaveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-account'
    | '/employee'
    | '/manager'
    | '/leaves-list/requests-list'
    | '/request-leaves/request-leave'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-account'
    | '/employee'
    | '/manager'
    | '/leaves-list/requests-list'
    | '/request-leaves/request-leave'
  id:
    | '__root__'
    | '/'
    | '/create-account'
    | '/employee'
    | '/manager'
    | '/leaves-list/requests-list'
    | '/request-leaves/request-leave'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateAccountRoute: typeof CreateAccountRoute
  EmployeeRoute: typeof EmployeeRoute
  ManagerRoute: typeof ManagerRoute
  LeavesListRequestsListRoute: typeof LeavesListRequestsListRoute
  RequestLeavesRequestLeaveRoute: typeof RequestLeavesRequestLeaveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-leaves/request-leave': {
      id: '/request-leaves/request-leave'
      path: '/request-leaves/request-leave'
      fullPath: '/request-leaves/request-leave'
      preLoaderRoute: typeof RequestLeavesRequestLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves-list/requests-list': {
      id: '/leaves-list/requests-list'
      path: '/leaves-list/requests-list'
      fullPath: '/leaves-list/requests-list'
      preLoaderRoute: typeof LeavesListRequestsListRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateAccountRoute: CreateAccountRoute,
  EmployeeRoute: EmployeeRoute,
  ManagerRoute: ManagerRoute,
  LeavesListRequestsListRoute: LeavesListRequestsListRoute,
  RequestLeavesRequestLeaveRoute: RequestLeavesRequestLeaveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
